### ISSUE TITLE
SGP40 module testing

### ISSUE THREAD

**Issue by pankaj4007** [CU-ECEN-5823/ecen5823-courseproject-adityavarshney100#1]
DoD: Should be able to read the TVOC readings from the module and display it using on the UART Terminal

**Comment by adityavarshney100** [comment]
Successfully able to verify the working of SGP40 air quality sensor. 
The screenshot of the assembly can be found below
![IMG_20210409_200702](https://user-images.githubusercontent.com/70616478/114258740-05fbfd80-9986-11eb-9a18-5669a092d045.jpg)
Also find below the screenshot of the readings from the Serial monitor using Arduino IDE
![SGP40 test](https://user-images.githubusercontent.com/70616478/114258779-4bb8c600-9986-11eb-9576-a9868e377677.JPG)
