### ISSUE TITLE
Relay integration on Client

### ISSUE THREAD

**Issue by pankaj4007** [CU-ECEN-5823/ecen5823-courseproject-adityavarshney100#4]
DoD: Should be able to integrate the relay on the gecko board and the gecko board should act as a client in the same program

**Comment by adityavarshney100** [comment]
Successfully able to communicate between the Gecko board and the relay.
Implemented a test function that turns on the relay and turns off the relay after a certain amount of time. 
![IMG_20210416_212019](https://user-images.githubusercontent.com/70616478/115100512-647f2980-9efa-11eb-95cf-629fb35234fe.jpg)
Next step is to receive commands from the Server to switch on and off the relay as per the measured air quality
